---
title: "Untitled"
author: "Huy Ngo"
date: "10/27/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(digits = 3)
```

```{r load-sas-libraries, echo = F, message = F, warning = F}

library(SASmarkdown)
sas_enginesetup(sashtml=sashtml)

sasexe <- "C:/Program Files/SASHome/SASFoundation/9.4/sas.exe"
sasopts <- "-nosplash -ls 75"

# Linux options (for grading, please leave this in!)
# sasexe <- "/usr/local/SASHome/SASFoundation/9.4/bin/sas_en"
# sasopts <- "-ls 75"
```


## Introduction

- This data is about Accidents recorded 

```{r, echo=FALSE, message=FALSE, warning=FALSE} 
#Reading data in R
library(dplyr)
library(readr)
Crash <- read_csv("monroe-county-crash-data2003-to-2015.csv")
head(Crash,10)

```

```{r}

```

## Methods


## Analysis
```{r, engine="sashtml", engine.path=sasexe, engine.opts=sasopts, collectcode = T, error = T, echo=FALSE, message=FALSE, warning=FALSE}
ODS HTML STYLE=HTMLBLUE;
filename dat "monroe-county-crash-data2003-to-2015.csv";
PROC IMPORT DATAFILE = dat OUT = Crash
    DBMS = CSV 
    REPLACE; 
    GETNAMES = YES;
    GUESSINGROWS = 5000;
RUN;

title "when and how";
PROC SGPLOT data=Crash;
SCATTER x = Year y = Primary_Factor / Group = Month;
RUN;    
```